compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1109627

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@metamask/*"
  - "@metamask-previews/*"
  - "@lavamoat/*"
  - "@consensys/*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
